'use server';
/**
 * @fileOverview This file defines a Genkit flow for generating and managing code.
 * It includes tools for file operations so the AI can perform workspace tasks.
 *
 * - generateCode - A function that handles the code generation process.
 * - AiCodeGenerationInput - The input type for the generateCode function.
 * - AiCodeGenerationOutput - The return type for the generateCode function.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';

// Define the operations the AI can suggest
const FileOperationSchema = z.object({
  type: z.enum(['createFile', 'updateFile', 'deleteFile', 'renameFile', 'createFolder']),
  path: z.string().describe('The path of the file or folder (e.g., "src/index.ts")'),
  content: z.string().optional().describe('Content for creation or update'),
  newName: z.string().optional().describe('New name for renaming'),
});

// 1. Define Input Schema
const AiCodeGenerationInputSchema = z.object({
  userPrompt: z.string().describe('The user\'s request for code generation or workspace management.'),
  programmingLanguage: z.string().describe('The desired programming language for the generated code.'),
  complexityLevel: z.enum(['simple', 'medium', 'complex']).describe('The desired complexity level.'),
  workspaceContext: z.array(z.object({
    path: z.string(),
    type: z.enum(['file', 'folder']),
    content: z.string().optional()
  })).optional().describe('Context of the existing files in the workspace.'),
});
export type AiCodeGenerationInput = z.infer<typeof AiCodeGenerationInputSchema>;

// 2. Define Output Schema
const AiCodeGenerationOutputSchema = z.object({
  generatedCode: z.string().describe('The main code generated by the AI if applicable.'),
  explanation: z.string().describe('A brief explanation of the actions taken or code generated.'),
  operations: z.array(FileOperationSchema).optional().describe('A list of file operations to perform on the workspace.'),
});
export type AiCodeGenerationOutput = z.infer<typeof AiCodeGenerationOutputSchema>;

// 3. Define the Genkit Prompt
const codeGenerationPrompt = ai.definePrompt({
  name: 'codeGenerationPrompt',
  input: { schema: AiCodeGenerationInputSchema },
  output: { schema: AiCodeGenerationOutputSchema },
  prompt: `You are an expert software developer and architect.
Your task is to fulfill the user's request. You can generate modular code and perform workspace operations.

If the user asks to build something complex, break it down into multiple file operations.
If the user asks to rename or delete something, use the appropriate operations.

Workspace Context:
{{#each workspaceContext}}
- {{{type}}}: {{{path}}}
{{#if content}}
  Content:
  \`\`\`
  {{{content}}}
  \`\`\`
{{/if}}
{{/each}}

User Prompt: {{{userPrompt}}}
Programming Language: {{{programmingLanguage}}}
Complexity Level: {{{complexityLevel}}}

IMPORTANT: Return a list of 'operations' if you need to create, update, rename, or delete files/folders.
`,
});

// 4. Define the Genkit Flow
const aiCodeGenerationFlow = ai.defineFlow(
  {
    name: 'aiCodeGenerationFlow',
    inputSchema: AiCodeGenerationInputSchema,
    outputSchema: AiCodeGenerationOutputSchema,
  },
  async (input) => {
    const { output } = await codeGenerationPrompt(input);
    if (!output) {
      throw new Error('Failed to generate response.');
    }
    return output;
  }
);

// 5. Define the exported wrapper function
export async function generateCode(input: AiCodeGenerationInput): Promise<AiCodeGenerationOutput> {
  return aiCodeGenerationFlow(input);
}
