'use server';
/**
 * @fileOverview This file defines a Genkit flow for generating code based on user prompts.
 *
 * - generateCode - A function that handles the code generation process.
 * - AiCodeGenerationInput - The input type for the generateCode function.
 * - AiCodeGenerationOutput - The return type for the generateCode function.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';

// 1. Define Input Schema
const AiCodeGenerationInputSchema = z.object({
  userPrompt: z.string().describe('The user\'s request for code generation.'),
  programmingLanguage: z.string().describe('The desired programming language for the generated code (e.g., Python, JavaScript, TypeScript, Java, C++, Go).'),
  complexityLevel: z.enum(['simple', 'medium', 'complex']).describe('The desired complexity level for the generated code. "simple" for basic examples, "medium" for standard functionalities, "complex" for advanced or optimized solutions.'),
});
export type AiCodeGenerationInput = z.infer<typeof AiCodeGenerationInputSchema>;

// 2. Define Output Schema
const AiCodeGenerationOutputSchema = z.object({
  generatedCode: z.string().describe('The code generated by the AI.'),
  explanation: z.string().describe('A brief explanation of the generated code.'),
});
export type AiCodeGenerationOutput = z.infer<typeof AiCodeGenerationOutputSchema>;

// 3. Define the Genkit Prompt
const codeGenerationPrompt = ai.definePrompt({
  name: 'codeGenerationPrompt',
  input: { schema: AiCodeGenerationInputSchema },
  output: { schema: AiCodeGenerationOutputSchema },
  prompt: `You are an expert software developer capable of generating modular code in various programming languages.
Your task is to generate code based on the user's prompt, in the specified programming language and complexity level.
Ensure the code is modular, well-structured, and includes comments where necessary.
Provide a brief explanation of the generated code.

The output should be a JSON object with two fields: "generatedCode" containing the code in a markdown code block, and "explanation" containing a brief explanation of the generated code.

---
User Prompt: {{{userPrompt}}}
Programming Language: {{{programmingLanguage}}}
Complexity Level: {{{complexityLevel}}}
`,
});

// 4. Define the Genkit Flow
const aiCodeGenerationFlow = ai.defineFlow(
  {
    name: 'aiCodeGenerationFlow',
    inputSchema: AiCodeGenerationInputSchema,
    outputSchema: AiCodeGenerationOutputSchema,
  },
  async (input) => {
    const { output } = await codeGenerationPrompt(input);
    if (!output) {
      throw new Error('Failed to generate code.');
    }
    return output;
  }
);

// 5. Define the exported wrapper function
export async function generateCode(input: AiCodeGenerationInput): Promise<AiCodeGenerationOutput> {
  return aiCodeGenerationFlow(input);
}
